<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7aaf78bbf89d721fb852bc6698fa7ff6
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Kirki\\Settings\\' => 15,
            'Kirki\\Module\\' => 13,
            'Kirki\\Field\\' => 12,
            'Kirki\\Core\\' => 11,
            'Kirki\\Control\\' => 14,
            'Kirki\\Compatibility\\' => 20,
            'Kirki\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Kirki\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/control-repeater/src/Settings',
        ),
        'Kirki\\Module\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/module-css/src',
            1 => __DIR__ . '/..' . '/kirki-framework/module-css-vars/src',
            2 => __DIR__ . '/..' . '/kirki-framework/module-custom-sections/src',
            3 => __DIR__ . '/..' . '/kirki-framework/module-editor-styles/src',
            4 => __DIR__ . '/..' . '/kirki-framework/module-field-dependencies/src',
            5 => __DIR__ . '/..' . '/kirki-framework/module-loading/src',
            6 => __DIR__ . '/..' . '/kirki-framework/module-postmessage/src',
            7 => __DIR__ . '/..' . '/kirki-framework/module-selective-refresh/src',
            8 => __DIR__ . '/..' . '/kirki-framework/module-tooltips/src',
            9 => __DIR__ . '/..' . '/kirki-framework/module-webfonts/src',
        ),
        'Kirki\\Field\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/control-checkbox/src/Field',
            1 => __DIR__ . '/..' . '/kirki-framework/control-color/src/Field',
            2 => __DIR__ . '/..' . '/kirki-framework/control-custom/src/Field',
            3 => __DIR__ . '/..' . '/kirki-framework/control-dimension/src/Field',
            4 => __DIR__ . '/..' . '/kirki-framework/control-editor/src/Field',
            5 => __DIR__ . '/..' . '/kirki-framework/control-generic/src/Field',
            6 => __DIR__ . '/..' . '/kirki-framework/control-image/src/Field',
            7 => __DIR__ . '/..' . '/kirki-framework/control-multicheck/src/Field',
            8 => __DIR__ . '/..' . '/kirki-framework/control-palette/src/Field',
            9 => __DIR__ . '/..' . '/kirki-framework/control-radio/src/Field',
            10 => __DIR__ . '/..' . '/kirki-framework/control-repeater/src/Field',
            11 => __DIR__ . '/..' . '/kirki-framework/control-select/src/Field',
            12 => __DIR__ . '/..' . '/kirki-framework/control-slider/src/Field',
            13 => __DIR__ . '/..' . '/kirki-framework/control-sortable/src/Field',
            14 => __DIR__ . '/..' . '/kirki-framework/control-upload/src/Field',
            15 => __DIR__ . '/..' . '/kirki-framework/field-background/src',
            16 => __DIR__ . '/..' . '/kirki-framework/field-dimensions/src',
            17 => __DIR__ . '/..' . '/kirki-framework/field-multicolor/src/Field',
            18 => __DIR__ . '/..' . '/kirki-framework/field-typography/src/Field',
        ),
        'Kirki\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/core/src',
        ),
        'Kirki\\Control\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/control-base/src/Control',
            1 => __DIR__ . '/..' . '/kirki-framework/control-checkbox/src/Control',
            2 => __DIR__ . '/..' . '/kirki-framework/control-color/src/Control',
            3 => __DIR__ . '/..' . '/kirki-framework/control-custom/src/Control',
            4 => __DIR__ . '/..' . '/kirki-framework/control-dimension/src/Control',
            5 => __DIR__ . '/..' . '/kirki-framework/control-editor/src/Control',
            6 => __DIR__ . '/..' . '/kirki-framework/control-generic/src/Control',
            7 => __DIR__ . '/..' . '/kirki-framework/control-image/src/Control',
            8 => __DIR__ . '/..' . '/kirki-framework/control-multicheck/src/Control',
            9 => __DIR__ . '/..' . '/kirki-framework/control-palette/src/Control',
            10 => __DIR__ . '/..' . '/kirki-framework/control-radio/src/Control',
            11 => __DIR__ . '/..' . '/kirki-framework/control-repeater/src/Control',
            12 => __DIR__ . '/..' . '/kirki-framework/control-select/src/Control',
            13 => __DIR__ . '/..' . '/kirki-framework/control-slider/src/Control',
            14 => __DIR__ . '/..' . '/kirki-framework/control-sortable/src/Control',
            15 => __DIR__ . '/..' . '/kirki-framework/field-multicolor/src/Control',
            16 => __DIR__ . '/..' . '/kirki-framework/field-typography/src/Control',
        ),
        'Kirki\\Compatibility\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/compatibility/src',
        ),
        'Kirki\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/field/src',
            1 => __DIR__ . '/..' . '/kirki-framework/googlefonts/src',
            2 => __DIR__ . '/..' . '/kirki-framework/url-getter/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7aaf78bbf89d721fb852bc6698fa7ff6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7aaf78bbf89d721fb852bc6698fa7ff6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
